# Generated by Django 4.1.4 on 2023-05-21 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_guest_table_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 8, 33, 13, 406014)),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 8, 33, 13, 406035)),
        ),
    ]
