# Generated by Django 4.1.4 on 2023-05-21 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_booking_check_in_booking_check_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='check_out',
        ),
        migrations.AddField(
            model_name='booking',
            name='from_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 12, 35, 22, 196327)),
        ),
        migrations.AddField(
            model_name='booking',
            name='to_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 12, 35, 22, 196346)),
        ),
    ]
