# Generated by Django 4.1.4 on 2023-05-21 12:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0005_rename_table_table_guests_alter_booking_from_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='from_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 12, 56, 19, 108954)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='to_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 12, 56, 19, 108972)),
        ),
        migrations.AlterField(
            model_name='table',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
