# Generated by Django 4.1.4 on 2023-05-21 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_booking_from_time_alter_booking_to_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='from_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 13, 0, 13, 497615)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='to_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 13, 0, 13, 497632)),
        ),
    ]
