# Generated by Django 4.1.4 on 2023-05-21 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_booking_from_time_alter_booking_to_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='table_name',
            field=models.CharField(default='default_tables1', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='from_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 13, 7, 25, 367149)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='to_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 13, 7, 25, 367167)),
        ),
    ]
