# Generated by Django 4.1.4 on 2023-05-21 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_booking_from_time_alter_booking_to_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='special_request',
            field=models.TextField(default='Nothing to Add Special', max_length=400),
        ),
        migrations.AlterField(
            model_name='booking',
            name='from_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 14, 33, 14, 824617)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='to_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 14, 33, 14, 824641)),
        ),
    ]
