# Generated by Django 4.1.4 on 2023-05-21 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_booking_special_request_alter_booking_from_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 15, 21, 44, 631210)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='from_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 15, 21, 44, 631185)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='to_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 15, 21, 44, 631204)),
        ),
    ]
