# Generated by Django 4.1.4 on 2023-05-21 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_booking_check_in_alter_booking_from_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='guest_cnic',
        ),
        migrations.AddField(
            model_name='guest',
            name='guest_phone',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 15, 38, 0, 865958)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='from_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 15, 38, 0, 865930)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='to_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 21, 15, 38, 0, 865950)),
        ),
    ]
