# Generated by Django 4.2.1 on 2023-05-28 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_remove_guest_guest_cnic_guest_guest_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 28, 11, 9, 45, 810198)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='from_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 28, 11, 9, 45, 810166)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='to_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 28, 11, 9, 45, 810189)),
        ),
        migrations.AlterField(
            model_name='guest',
            name='guest_phone',
            field=models.TextField(null=True),
        ),
    ]
