# Generated by Django 4.2.1 on 2023-05-28 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_booking_check_in_alter_booking_from_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
